#!/bin/sh
docker container run --rm --net moodle-net mariadb:latest mysqldump -h dbserver-moodle -u moodle_user --password=4linux moodle > /tmp/moodle-db-backup-$(date '+%d-%m-%Y').sql

aws s3 cp /tmp/moodle_db_backup-$(date '+%d-%m-%Y').sql s3://backup-moodle-aws/banco/
